export enum CONSTANTS_KEYS {
	TIMERS_STATE = 'TIMERS_STATE',
	STATE_THROTTLE = 'STATE_THROTTLE',
	STATE_INTERVAL = 'STATE_INTERVAL',
	MS_VALUE = 'MS_VALUE',
	MS_SECS = 'MS_SECS',
	MS_MINS = 'MS_MINS',
	MS_HOURS = 'MS_HOURS',
	MS_ROUND = 'MS_ROUND',
	HOUR_ROUND = 'HOUR_ROUND',
}

export const CONSTANTS_VALUES = {
	[CONSTANTS_KEYS.STATE_THROTTLE]: 1000,
	[CONSTANTS_KEYS.STATE_INTERVAL]: 50,
	[CONSTANTS_KEYS.MS_VALUE]: 100,
	[CONSTANTS_KEYS.MS_SECS]: 1000,
	[CONSTANTS_KEYS.MS_MINS]: 1000,
	[CONSTANTS_KEYS.MS_HOURS]: 60,
	[CONSTANTS_KEYS.MS_ROUND]: 10,
	[CONSTANTS_KEYS.HOUR_ROUND]: 60,
};
